export const INFO_AFTER_LOGIN = 'INFO_AFTER_LOGIN';
export const DELETE_INFO_AFTER_LOGOUT = 'DELETE_INFO_AFTER_LOGOUT';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';